#!/bin/bash

############################################################################################################################
# ardopgui
#
# Script to setup and install the gui interface for the ardop protocol for winlink
#
# Author: Mike Myers (K3DO)
#
# This is a project of the Mid Atlantic Wireless Communication Group
# http://mawcg.org
############################################################################################################################

echo " =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-" >> $1
echo " =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-" >> $1
echo "ARDOP GUI Installation Started at `date`" >> $1
echo " " >> $1
echo " " >> $1

#####################################
# Installing
#####################################

mkdir -p $3/ardop
cd $3/ardop
wget https://www.cantab.net/users/john.wiseman/Downloads/Beta/piARDOP_GUI || echo "*** ERROR ***  Can't download piARDOP_GUI" >> $1
sudo chmod +x $3/ardop/piARDOP_GUI

#####################################
# Creating Desktop Icon
#####################################

cat > ardopgui.desktop <<EOF
[Desktop Entry]
Name=ARDOP GUI
GenericName=ARDOP GUI
Comment=Graphical User Interface for ARDOP modem
Exec=$3/ardop/piARDOP_GUI
Terminal=false
Type=Application
Categories=Network;HamRadio;
EOF

sudo mv ardopgui.desktop /usr/share/applications/


#####################################
# Create Config File
#####################################

FILE=$3/.config/G8BPQ/ARDOP_GUI.conf
mkdir -p $3/.config/G8BPQ
touch $FILE
echo "[General]" >> $FILE
echo "Port=8515" >> $FILE
echo "Host=local" >> $FILE

echo " " >> $1
echo " " >> $1
echo "ARDOP GUI install completed  at `date`" >> $1
echo " " >> $1
echo " =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-" >> $1
echo " =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-" >> $1
