#!/bin/bash

############################################################################################################################
# contestlogger
#
# Script to setup and install the web based contest logger software
#
# Author: Mike Myers (K3DO)
#
# This is a project of the Mid Atlantic Wireless Communication Group
# http://mawcg.org
############################################################################################################################

