#!/bin/bash

############################################################################################################################
# crqlog
#
# Script to setup and install the crqlog logging tool
#
# Author: Mike Myers (K3DO)
#
# This is a project of the Mid Atlantic Wireless Communication Group
# http://mawcg.org
############################################################################################################################

echo " =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-" >> $1
echo " =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-" >> $1
echo "CRQLOG Installation Started at `date`" >> $1
echo " " >> $1
echo " " >> $1

#####################################
# Installing
#####################################

echo " "
echo "Installing Packages..."
echo " "

sudo apt-get install -y cqrlog

echo " "
echo "Updating Start Menu..."
echo " "

sed -i 's/Categories=Utility;Database;HamRadio/Categories=HamRadio/' /usr/share/applications/cqrlog.desktop


echo " " >> $1
echo " " >> $1
echo "CRQLOG install completed  at `date`" >> $1
echo " " >> $1
echo " =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-" >> $1
echo " =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-" >> $1
