#!/bin/bash

############################################################################################################################
# direwolf
#
# Script to setup and install the direwolf virtual tnc
#
# Author: Mike Myers (K3DO)
#
# This is a project of the Mid Atlantic Wireless Communication Group
# http://mawcg.org
############################################################################################################################

echo " =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-" >> $1
echo " =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-" >> $1
echo "DIREWOLF Installation Started at `date`" >> $1
echo " " >> $1
echo " " >> $1

#####################################
# Installing
#####################################
echo "Downloading Source Code..."
echo " "

cd $3
git clone https://www.github.com/wb2osz/direwolf  >> $1 2>1
cd $3/direwolf

echo " "
echo "Installing Dependencies..."
echo " "
sudo apt-get install cmake
sudo apt-get install -y libasound2-dev
sudo apt-get install libudev-dev

echo " "
echo "Compiling..."
echo " "

mkdir build
cd build
cmake -DUNITTEST=1 ..
make -j4
make test

echo " "
echo "Installing..."
echo " "
sudo make install
make install-conf

#####################################
# Modify Config File
#####################################
mv $HOME/direwolf.conf /etc
sed -i "s/N0CALL/$4/" "/etc/direwolf.conf"
sed -i 's/# ADEVICE  plughw:1,0/ADEVICE  plughw:1,0/' $3/direwolf.conf

#####################################
# Cleanup Build Directory
#####################################

rm -rf $3/direwolf

echo " "
echo "Done..."
echo " "

echo " " >> $1
echo " " >> $1
echo "DIREWOLF install completed  at `date`" >> $1
echo " " >> $1
echo " =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-" >> $1
echo " =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-" >> $1
