#!/bin/bash

############################################################################################################################
# fldigi
#
# Script to setup and install the fldigi digital application
#
# Author: Mike Myers (K3DO)
#
# This is a project of the Mid Atlantic Wireless Communication Group
# http://mawcg.org
############################################################################################################################

sudo apt install -y fldigi
echo "FLDIGI installed repository" >> $BUILDLOG
