#!/bin/bash

############################################################################################################################
# fldigi
#
# Script to setup and install the fldigi digital application
#
# Author: Mike Myers (K3DO)
#
# This is a project of the Mid Atlantic Wireless Communication Group
# http://mawcg.org
############################################################################################################################

echo " =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-" >> $1
echo " =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-" >> $1
echo "FLDIGI Installation Started at `date`" >> $1
echo " " >> $1
echo " " >> $1

#####################################
# Installing
#####################################

echo " "
echo "Installing Packages..."
echo " "

sudo apt-get install -y fldigi

echo " "
echo "Updating Start Menu..."
echo " "

sed -i 's/Categories=Network;HamRadio/Categories=HamRadio/' /usr/share/applications/fldigi.desktop
sed -i 's/Categories=Network;HamRadio/Categories=HamRadio/' /usr/share/applications/flarq.desktop

echo " " >> $1
echo " " >> $1
echo "FLDIGI install completed  at `date`" >> $1
echo " " >> $1
echo " =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-" >> $1
echo " =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-" >> $1
