#!/bin/bash

############################################################################################################################
# gARIM
#
# Script to setup and install the gARIM Chat tools
#
# Author: Mike Myers (K3DO)
#
# This is a project of the Mid Atlantic Wireless Communication Group
# http://mawcg.org
############################################################################################################################

echo " =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-" >> $1
echo " =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-" >> $1
echo "gARIM Installation Started at `date`" >> $1
echo " " >> $1
echo " " >> $1

#####################################
# Download and Extract Source Code
#####################################
cd $3

echo " "
echo "Installing Prerequisites..."
echo " "

sudo apt-get install -y fluid

echo " "
echo "Downloading and Installing Application..."
echo " "

wget https://www.whitemesa.net/garim/src/garim-1.4.tar.gz 
tar xzvf garim-1.4.tar.gz
rm garim-1.4.tar.gz
cd $3/garim-1.4

#####################################
# Build gARIM
#####################################
./configure
make

#####################################
# Installing gARIM
#####################################
sudo make install

echo " " >> $1
echo " " >> $1
echo "gARIM install completed  at `date`" >> $1
echo " " >> $1
echo " =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-" >> $1
echo " =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-" >> $1

