#!/bin/bash

############################################################################################################################
# gpredict
#
# Script to setup and install the gpredict satelite tracking software
#
# Author: Mike Myers (K3DO)
#
# This is a project of the Mid Atlantic Wireless Communication Group
# http://mawcg.org
############################################################################################################################

sudo apt-get install -y gpredict

