#!/bin/bash

############################################################################################################################
# GPS
#
# Script to setup and install GPS
#
# Author: Mike Myers (K3DO)
#
# This is a project of the Mid Atlantic Wireless Communication Group
# http://mawcg.org
############################################################################################################################

echo " =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-" >> $1
echo " =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-" >> $1
echo "GPS Installation Started at `date`" >> $1
echo " " >> $1
echo " " >> $1

#####################################
# Installing
#####################################


echo " "
echo "Installing Prerequisites..."
echo " "

sudo apt-get install -y gpsd gpsd-clients python-gps chrony
sudo nano /etc/default/gpsd
# Make / change to following setting:
START_DAEMON=”true”
USBAUTO=”true”
DEVICES=”/dev/ttyACM0″
GPSD_OPTIONS=”-n”
#Ctrl-X and yes to save
sudo nano /etc/chrony/chrony.conf
#Add the following line to the end of the file:
refclock SHM 0 offset 0.5 delay 0.2 refid NMEA

echo " "
echo "Cleaning Up..."
echo " "

rm -fr $2/*


echo " " >> $1
echo " " >> $1
echo "GPS install completed  at `date`" >> $1
echo " " >> $1
echo " =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-" >> $1
echo " =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-" >> $1