#!/bin/bash

############################################################################################################################
# hamlib
#
# Script to setup and install the hamlib unix tools
#
# Author: Mike Myers (K3DO)
#
# This is a project of the Mid Atlantic Wireless Communication Group
# http://mawcg.org
############################################################################################################################

echo " =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-" >> $1
echo " =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-" >> $1
echo "HAMLIB Installation Started at `date`" >> $1
echo " " >> $1
echo " " >> $1

#####################################
# Installing
#####################################

echo "Downloading Packages..."
echo " "

cd $2
wget https://sourceforge.net/projects/hamlib/files/hamlib/3.3/hamlib-3.3.tar.gz  >> $1 2>1

echo " "
echo "Installing Packages..."
echo " "

tar -xzf $2/hamlib-3.3.tar.gz
rm $2/hamlib-3.3.tar.gz
cd $2/hamlib-3.3
./configure 2>$1
make 2>$1
sudo make install
sudo ldconfig

echo " "
echo "Updating Start Menu..."
echo " "

sed -i 's/Categories=AudioVideo;Audio;HamRadio;/Categories=HamRadio/' /usr/share/applications/hamlib.desktop

echo " "
echo "Cleaning Up..."
echo " "

rm -fr $2/*

echo " " >> $1
echo " " >> $1
echo "HAMLIB install completed  at `date`" >> $1
echo " " >> $1
echo " =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-" >> $1
echo " =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-" >> $1
