#!/bin/bash

############################################################################################################################
# M0IAX
#
# Script to setup and install the tools and programs needed for M0AIX
#
# Author: Mike Myers (K3DO)
#
# This is a project of the Mid Atlantic Wireless Communication Group
# http://mawcg.org
############################################################################################################################

echo " =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-" >> $1
echo " =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-" >> $1
echo "M0IAX Installation Started at `date`" >> $1
echo " " >> $1
echo " " >> $1

#####################################
# Installing Needed Python Libraries
#####################################

echo " "
echo "Installing Python Packages..."
echo " "

pip3 install gps
pip3 install maidenhead
pip3 install psutil
pip3 install OSGridConverter

#####################################
# Installing Application
#####################################

echo " "
echo "Downloading..."
echo " "

if [ ! -d "$3/JS8Tools" ] 
then
   mkdir $3/JS8Tools 
fi

cd $3/JS8Tools
git clone https://github.com/m0iax/JS8CallUtilities_V2.git >> $1 2>1
chmod +x $3/JS8Tools/JS8CallUtilities_V2/gpsdGPSListener.py $3/JS8Tools/JS8CallUtilities_V2/JS8CallUtils_v2.py
mv $3/JS8Tools/JS8CallUtilities_V2/* $3/JS8Tools
rm -rf JS8CallUtilities_V2


#####################################
# Creating Desktop Icon
#####################################

echo " "
echo "Creating Start Menu Item..."
echo " "

cat > js8tools.desktop <<EOF
[Desktop Entry]
Name=M0IAX JS8 Tools
GenericName=M0IAX JS8 Tools
Comment=GPS & Message Tool for JS8Call
Exec=$3/JS8Tools/JS8CallUtils_v2.py
Terminal=false
Type=Application
Categories=HamRadio;
EOF

sudo mv js8tools.desktop /usr/share/applications/

echo " " >> $1
echo " " >> $1
echo "M0IAX Tools install completed  at `date`" >> $1
echo " " >> $1
echo " =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-" >> $1
echo " =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-" >> $1
