#!/bin/bash

############################################################################################################################
# MeshMap
#
# Script to setup and install MeshMap for AREDN
#
# Author: Mike Myers (K3DO)
#
# This is a project of the Mid Atlantic Wireless Communication Group
# http://mawcg.org
############################################################################################################################

echo " =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-" >> $1
echo " =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-" >> $1
echo "MeshMap Installation Started at `date`" >> $1
echo " " >> $1
echo " " >> $1

#####################################
# Installing
#####################################


echo " "
echo "Installing Prerequisites..."
echo " "

sudo apt-get install -y php7.3 mariadb-server
sudo apt-get install -y apache2

echo " "
echo "Installing MsshMap..."
echo " "

cd $2
git clone https://mapping.kg6wxc.net/git/meshmap
cd meshmap

echo " "
echo "Creating Database..."
echo " "

echo "CREATE USER 'mesh-map'@'localhost' IDENTIFIED BY 'M3shM@pPa$$';" >> node_map.sql
echo "GRANT ALL PRIVILEGES on node_map.* TO 'mesh-map'@'localhost';" >> node_map.sql
echo "FLUSH PRIVILEGES" >> node_map.sql

sudo mysql < node_map.sql

echo " "
echo "Configuring..."
echo " "

cp scripts/user-settings.ini-default scripts/user-settings.ini

sed -i 's/mesh-map_sql_user_password/M3shM@pPa$$/' ./scripts/user-settings.ini


sudo mkdir /var/www/html/meshmap
sudo chmod 755 /var/www/html/meshmap
sudo chown www-data:www-data /var/www/html/meshmap
cp -r * /var/www/html/meshmap 

echo " "
echo "Installing Menu..."
echo " "

cat > meshmap.desktop <<EOF
[Desktop Entry]
Name=MeshMap
GenericName=AREDN MeshMap
Comment=AREDN MeshMap
Exec=/usr/bin/chromium-browser http://localhost/meshmap
Terminal=false
Type=Application
Categories=HamRadio;
EOF

sudo mv meshmap.desktop /usr/share/applications/

echo " "
echo "Cleaning Up..."
echo " "

rm -fr $2/*


echo " " >> $1
echo " " >> $1
echo "MeshMap install completed  at `date`" >> $1
echo " " >> $1
echo " =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-" >> $1
echo " =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-" >> $1