#!/bin/bash

############################################################################################################################
# pat
#
# Script to setup and install the pat winlink client
#
# Author: Mike Myers (K3DO)
#
# This is a project of the Mid Atlantic Wireless Communication Group
# http://mawcg.org
############################################################################################################################

echo " =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-" >> $1
echo " =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-" >> $1
echo "Pat Installation Started at `date`" >> $1
echo " " >> $1
echo " " >> $1

#####################################
# Installing
#####################################

echo " "
echo "Downloading and Installing Application..."
echo " "

cd $2
wget https://github.com/la5nta/pat/releases/download/v0.9.0/pat_0.9.0_linux_armhf.deb >> $1 2>1
sudo dpkg -i pat_0.9.0_linux_armhf.deb


echo " "
echo "Configuring Pat..."
echo " "

pat rmslist >> $1 2>1

sudo cp -r /root/.wl2k /home/pi
sudo chown -R pi /home/pi/.wl2k

sed -i "s/mycall\":\ \"\"/mycall\":\ \"$4\"/" /home/pi/.wl2k/config.json
sed -i "s/locator\":\ \"\"/Locator\":\ \"$5\"/" /home/pi/.wl2k/config.json
sed -i "s/secure_login_password\":\ \"\"/secure_login_password\":\ \"$6\"/" /home/pi/.wl2k/config.json


echo " "
echo "Starting Pat..."
echo " "

sudo systemctl start pat@pi
sudo systemctl enable pat@pi

echo " "
echo "Installing Shortcuts..."
echo " "

#####################################
# Install GPS if selected
#####################################

#enable gps in pat is gps=yes
if [ $GPS = "yes" ]
then
	sed -i 's/"enable_http": false,/"enable_http": true,/' /home/pi/.wl2k/config.json
fi

echo " " >> $1
echo " " >> $1
echo "Pat install completed  at `date`" >> $1
echo " " >> $1
echo " =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-" >> $1
echo " =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-" >> $1
