#!/bin/bash

############################################################################################################################
# piardop
#
# Script to setup and install the ardop protocol for winlink
#
# Author: Mike Myers (K3DO)
#
# This is a project of the Mid Atlantic Wireless Communication Group
# http://mawcg.org
############################################################################################################################

echo " =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-" >> $1
echo " =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-" >> $1
echo "PIARDOP Installation Started at `date`" >> $1
echo " " >> $1
echo " " >> $1

#####################################
# Installing
#####################################

mkdir -p $HOME/ardop
cd $HOME/ardop
wget https://www.cantab.net/users/john.wiseman/Downloads/Beta/piardopc || echo "*** ERROR ***  Can't download PIARDOPC" >> $1
sudo chmod +x $HOME/ardop/piardopc

echo " " >> $1
echo " " >> $1
echo "PIARDOP install completed  at `date`" >> $1
echo " " >> $1
echo " =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-" >> $1
echo " =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-" >> $1
