#!/bin/bash

############################################################################################################################
# propagation
#
# Script to setup and install the propagation gui tool
#
# Author: Mike Myers (K3DO)
#
# This is a project of the Mid Atlantic Wireless Communication Group
# http://mawcg.org
############################################################################################################################

echo " =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-" >> $1
echo " =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-" >> $1
echo "Propagation Installation Started at `date`" >> $1
echo " " >> $1
echo " " >> $1

#####################################
# Installing Supporting Libraries
#####################################

echo " "
echo "Installing Prerequisites..."
echo " "

sudo apt-get install -y gfortran yelp python3-gi python3-gi-cairo rarian-compat gnome-doc-utils pkg-config python3-dateutil python3-mpltoolkits.basemap python3-cairocffi libgtk-3-dev

#####################################
# Installing Application
#####################################

echo " "
echo "Download and Install application..."
echo " "

cd $2
wget https://www.qsl.net/hz1jw/voacapl/downloads/voacapl-0.7.2.tar.gz >> $1 2>1
tar -xzf voacapl-0.7.2.tar.gz
cd voacapl-0.7.2
./configure
make 2>>$1
sudo make install


#####################################
# Installing GUI Interface
#####################################

echo " "
echo "Download and Install GUI Interface..."
echo " "

cd $2
wget https://www.qsl.net/hz1jw/pythonprop/downloads/pythonprop-0.28.tar.gz >> $1 2>1
tar -xzf pythonprop-0.28.tar.gz
cd pythonprop-0.28
./configure
sudo make install

echo " "
echo "Updating Start Menu..."
echo " "

sed -i 's/Categories=Science;HamRadio/Categories=HamRadio;/' /usr/local/share/applications/voacapgui.desktop
sed -i 's/Name=voacapgui/Name=Propagation/' /usr/local/share/applications/voacapgui.desktop

echo " "
echo "Cleaning Up..."
echo " "

rm -fr $2/*

echo " " >> $1
echo " " >> $1
echo "Propagation install completed  at `date`" >> $1
echo " " >> $1
echo " =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-" >> $1
echo " =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-" >> $1
