#!/bin/bash

############################################################################################################################
# pyqso
#
# Script to setup and install the pyqso logging tool
#
# Author: Mike Myers (K3DO)
#
# This is a project of the Mid Atlantic Wireless Communication Group
# http://mawcg.org
############################################################################################################################

sudo apt-get install -y pyqso

