#!/bin/bash

############################################################################################################################
# systemupdate
#
# Script to perform a system update and upgrade
#
# Author: Mike Myers (K3DO)
#
# This is a project of the Mid Atlantic Wireless Communication Group
# http://mawcg.org
############################################################################################################################

echo " =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-" >> $1
echo " =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-" >> $1
echo "System Update Started at `date`" >> $1
echo " " >> $1
echo " " >> $1

echo "System Update Started at `date`"
echo " "
echo " "
sudo apt-get update
sudo apt-get upgrade

echo " " >> $1
echo " " >> $1
echo "System Update completed  at `date`" >> $1
echo " " >> $1
echo " =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-" >> $1
echo " =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-" >> $1
echo " "
echo "System Update Completed at `date`"
echo " "
echo "System Update Complete"
echo " "
echo " "
sleep 3
