#!/bin/bash

############################################################################################################################
# test
#
# Script to generate some output to test the menu-install without having to actually install something
#
# Author: Mike Myers (K3DO)
#
# This is a project of the Mid Atlantic Wireless Communication Group
# http://mawcg.org
############################################################################################################################

#du /
ls -al

echo "1: $1"
echo "2: $2"
echo "3: $3"
echo "4: $4"
echo "5: $5"
echo "6: $5"

sleep 10
