#!/bin/bash

############################################################################################################################
# yaac
#
# Script to setup and install the YAAC Tools
#
# Author: Mike Myers (K3DO)
#
# This is a project of the Mid Atlantic Wireless Communication Group
# http://mawcg.org
############################################################################################################################

echo " =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-" >> $1
echo " =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-" >> $1
echo "YACC Installation Started at `date`" >> $1
echo " " >> $1
echo " " >> $1

#####################################
# Installing
#####################################

if [ ! -d "$3/YAAC" ] 
then
   mkdir -p $3/YAAC 
fi

cd $3/YAAC

echo " "
echo "Installing Prerequisites..."
echo " "

sudo apt-get install -y openjdk-8-jre librxtx-java

echo " "
echo "Downloading and Installing Application..."
echo " "

wget https://www.ka2ddo.org/ka2ddo/YAAC.zip >> $1 2>1

unzip $3/YAAC/YAAC.zip
touch YAAC
echo "#!/bin/bash" >> YAAC
echo "java -jar $3/YAAC/YAAC.jar" >> YAAC
chmod +x YAAC


#####################################
# Create Desktop Icon
#####################################

echo " "
echo "Creating Start Menu Item..."
echo " "

cat > yaac.desktop <<EOF
[Desktop Entry]
Name=YAAC
GenericName=YAAC
Comment=APRS Client
Exec=$3/YAAC/YAAC
Terminal=false
Type=Application
Categories=HamRadio;
EOF

sudo mv yaac.desktop /usr/share/applications/

echo " "
echo "Cleaning Up..."
echo " "

rm -f $3/YAAC/YAAC.zip


echo " " >> $1
echo " " >> $1
echo "YACC install completed  at `date`" >> $1
echo " " >> $1
echo " =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-" >> $1
echo " =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-" >> $1
