#!/bin/bash

############################################################################################################################
# install-menu
#
# Script to install Ham Radio Tools on the Raspberry Pi easily.
#
# Author: Mike Myers (K3DO)
#
# This is a project of the Mid Atlantic Wireless Communication Group
# http://mawcg.org
############################################################################################################################

GRIDSQ=$($HOME/bin/conky/get-grid)
GRIDER=$(echo $GRIDSQ | grep -i JJ00)

############################################################################
# Check for a valid grid, on no return output the grid squsre that was 
# entered during install
############################################################################

if [ -z "$GRIDER" ]
then
echo $GRIDSQ
else
echo `cat $HOME/.ham-pi.grid`
fi
